### ISSUE TITLE
Convert colors to CSS variables

### ISSUE THREAD

**Issue by jessicard** [jessicard/hacker-challenge#12]
Right now we have [black](https://github.com/jessicard/hacker-challenge/blob/main/style.css#L21) and [green](https://github.com/jessicard/hacker-challenge/blob/main/style.css#L24) hex color codes in the CSS. Let's convert that and anything else that makes sense to use CSS variables. https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

**Comment by Nejilee** [comment]
Hey, can I work on this issue?

**Comment by jessicard** [comment]
@Nejilee Please do!

**Comment by jessicard** [comment]
Fixed in https://github.com/jessicard/hacker-challenge/pull/14, thanks @Nejilee !
